run:
  timeout: 5m
  allow-parallel-runners: true

linters:
  disable:
    - errcheck
    - unused
    - unparam
  enable:
    - govet
    - ineffassign
    - staticcheck
    - misspell

issues:
  exclude-dirs:
    - vendor
  max-issues-per-linter: 0
  max-same-issues: 0
